### ISSUE TITLE
Practica 8 Reconocimiento por GPS

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-equipo-gregorio-8us#1]
[P8_UbicacionGPS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-equipo-gregorio-8us/files/15201420/P8_UbicacionGPS.pdf)

**Comment by ElisabetRD** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
